### PR TITLE
📰 Update youtube_bot folder name

### PR DESCRIPTION
**Pull request by kadirnar**
The notebook link in this readme file doesn't work. Because the url is wrong. Also, youtube_bot isn't a correct folder name. It should be more readable. So I updated the folder name and readme file.

https://github.com/lancedb/vectordb-recipes/tree/main/examples/youtube_bot

### CODE REVIEW

**Comment by AyushExel** [comment]
@PrashantDixit0 can you check and merge?

**Comment by PrashantDixit0** [comment]
Sure I'll check and merge

**Comment by PrashantDixit0** [comment]
All looks good, Just the Folder name is changed and the Colab link is fixed. 
btw Node test is failing with `TypeError: Openai is not a constructor` error

**Comment by kadirnar** [comment]
> All looks good, Just the Folder name is changed and the Colab link is fixed. btw Node test is failing with `TypeError: Openai is not a constructor` error

Where is the openai.js file?
```bash
/home/runner/work/vectordb-recipes/vectordb-recipes/testing-folder/node_modules/vectordb/dist/embedding/openai.js:34
```

**Comment by PrashantDixit0** [comment]
This file is getting creating in test environment for tests, We'll check it @kadirnar and merge this PR

**Pull request merged**
