### PR TITLE
New Changes to VectorDb Examples - Jupyter Notebooks

### PR DESCRIPTION
**Pull request by kaushal07wick**
1. Added new infographics to the notebooks for better visibility
2.  Made necessary changes to the codes, related to installing and formatting

### CODE REVIEW

**Comment by AyushExel** [comment]
Screenshot 2023-10-20 at 10 44 01 AM

Getting this on the first notebook Code-QA bot

**Comment by AyushExel** [comment]
Fix the output in the audio example. This error message is saved in the log
Screenshot 2023-10-20 at 10 53 11 AM

**Comment by AyushExel** [comment]
Thanks other things look good. Just fix the other 2

**Comment by kaushal07wick** [comment]
> Collaborator

done, I accidently removed a trailing slash.

**Comment by kaushal07wick** [comment]
> Fix the output in the audio example. This error message is saved in the log Screenshot 2023-10-20 at 10 53 11 AM
> 
> Screenshot 2023-10-20 at 10 54 58 AM

removed the errors. thanks

**Pull request merged**
