### PR TITLE
HR chatboat 

### PR DESCRIPTION
**Pull request by akashAD98**
ask any query to hr chatbot application 

used zero-shot react agent & custom tools 
lanceddb as vector 
& openai or any open source llm model

### CODE REVIEW

**Comment by AyushExel** [comment]
@akashAD98 overall looks good.
1 thing we should probably change is how openai api key is handled. I haven't run this myself but I think that its not checking the openai api key in the os.environment?

The CLI usage should be something like this:
```
OPENAI_API_KEY=... streamlit ...
```
This way `OPENAI_API_KEY`will be accessible in as an enviroment variable. 
Can you make that change

**Comment by akashAD98** [comment]
@AyushExel okay ill add this code. should we add .env file & inside that we can assign this api

**Comment by AyushExel** [comment]
Maybe that won't be required. Basically anything you pass like this `OPENAI_API_KEY=...` before the main command like `python test.py` will automatically become environment variable. I think you can just check if that is set, and if that is not set, just simply ask for input using getpass()

**Comment by akashAD98** [comment]
i did changes & updated the readme. added .env variable option for openai key

**Pull request merged**
